# Generated by Django 5.1.1 on 2024-09-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_userprofile_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='store/usersimage'),
        ),
    ]
