# Generated by Django 5.1.1 on 2024-09-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
