# Generated by Django 5.1.1 on 2024-09-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0003_digital_product_brand_digital_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='media/banners/'),
        ),
    ]
