# Generated by Django 5.1.1 on 2024-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0004_alter_image_image'),
        ('app_social', '0003_rename_field_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_product',
            name='images',
            field=models.ManyToManyField(to='app_social.image'),
        ),
        migrations.AlterField(
            model_name='digital_product',
            name='images',
            field=models.ManyToManyField(to='app_social.image'),
        ),
    ]
