# Generated by Django 5.1.1 on 2024-09-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0005_alter_clothes_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes_product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='digital_product',
            name='images',
        ),
    ]
