# Generated by Django 5.1.1 on 2024-09-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0008_category_remove_clothes_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='field',
            new_name='color',
        ),
    ]
