# Generated by Django 5.1.1 on 2024-09-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0011_alter_image_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.RemoveField(
            model_name='digital_product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='digital_product',
            name='category',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='field',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_didikala.division'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('count', models.IntegerField(null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_didikala.brand')),
                ('categories', models.ManyToManyField(to='app_didikala.category')),
            ],
        ),
        migrations.DeleteModel(
            name='clothes_product',
        ),
        migrations.DeleteModel(
            name='color',
        ),
    ]
