# Generated by Django 5.1.1 on 2024-09-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0012_division_remove_color_product_and_more'),
        ('app_payment', '0002_alter_basket_item_product_alter_order_item_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='digital_product',
        ),
    ]
