# Generated by Django 5.1.1 on 2024-09-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0013_delete_digital_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='branch',
            new_name='division',
        ),
    ]
