# Generated by Django 5.1.1 on 2024-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0016_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
