# Generated by Django 5.1.1 on 2024-09-18 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0017_product_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetailDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app_didikala.detaildescription')),
            ],
        ),
        migrations.AddField(
            model_name='detaildescription',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_descriptions', to='app_didikala.img'),
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('specification_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='app_didikala.specificationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('code_number', models.CharField(max_length=50)),
                ('reviews', models.TextField()),
                ('colors', models.ManyToManyField(related_name='products', to='app_didikala.color')),
                ('descriptions', models.ManyToManyField(related_name='products', to='app_didikala.description')),
                ('images', models.ManyToManyField(related_name='products', to='app_didikala.img')),
                ('special_features', models.ManyToManyField(related_name='products', to='app_didikala.specialfeature')),
                ('specifications', models.ManyToManyField(related_name='products', to='app_didikala.specifications')),
            ],
        ),
    ]
