# Generated by Django 5.1.1 on 2024-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0020_color_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='description_detail',
        ),
        migrations.RemoveField(
            model_name='specifications',
            name='specification_detail',
        ),
        migrations.AddField(
            model_name='description',
            name='description_detail',
            field=models.ManyToManyField(related_name='descriptions', to='app_didikala.detaildescription'),
        ),
        migrations.AddField(
            model_name='specifications',
            name='specification_detail',
            field=models.ManyToManyField(related_name='specifications', to='app_didikala.specificationdetail'),
        ),
    ]
