# Generated by Django 5.1 on 2024-09-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0021_remove_description_description_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialfeature',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_didikala.category'),
        ),
        migrations.AddField(
            model_name='specifications',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_didikala.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
