# Generated by Django 5.1 on 2024-09-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0022_specialfeature_category_specifications_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('code_number', models.CharField(max_length=50)),
                ('reviews', models.TextField()),
                ('size', models.CharField(max_length=10)),
                ('descriptions', models.ManyToManyField(related_name='clothes_products', to='app_didikala.description')),
                ('images', models.ManyToManyField(related_name='clothes_products', to='app_didikala.img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_product_detail', to='app_didikala.product')),
                ('special_features', models.ManyToManyField(related_name='clothes_products', to='app_didikala.specialfeature')),
                ('specifications', models.ManyToManyField(related_name='clothes_products', to='app_didikala.specifications')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('code_number', models.CharField(max_length=50)),
                ('reviews', models.TextField()),
                ('colors', models.ManyToManyField(related_name='digital_products', to='app_didikala.color')),
                ('descriptions', models.ManyToManyField(related_name='digital_products', to='app_didikala.description')),
                ('images', models.ManyToManyField(related_name='digital_products', to='app_didikala.img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_product_detail', to='app_didikala.product')),
                ('special_features', models.ManyToManyField(related_name='digital_products', to='app_didikala.specialfeature')),
                ('specifications', models.ManyToManyField(related_name='digital_products', to='app_didikala.specifications')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
