# Generated by Django 5.1 on 2024-09-20 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0023_clothingproductdetail_digitalproductdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalproductdetail',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='digitalproductdetail',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='digitalproductdetail',
            name='images',
        ),
        migrations.RemoveField(
            model_name='digitalproductdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='digitalproductdetail',
            name='special_features',
        ),
        migrations.RemoveField(
            model_name='digitalproductdetail',
            name='specifications',
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('code_number', models.CharField(max_length=50)),
                ('reviews', models.TextField()),
                ('colors', models.ManyToManyField(related_name='products', to='app_didikala.color')),
                ('descriptions', models.ManyToManyField(related_name='products', to='app_didikala.description')),
                ('images', models.ManyToManyField(related_name='products', to='app_didikala.img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='app_didikala.product')),
                ('special_features', models.ManyToManyField(related_name='products', to='app_didikala.specialfeature')),
                ('specifications', models.ManyToManyField(related_name='products', to='app_didikala.specifications')),
            ],
        ),
        migrations.DeleteModel(
            name='ClothingProductDetail',
        ),
        migrations.DeleteModel(
            name='DigitalProductDetail',
        ),
    ]
