# Generated by Django 5.1 on 2024-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0024_remove_digitalproductdetail_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='descriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='app_didikala.description'),
        ),
    ]
