# Generated by Django 5.1 on 2024-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0025_alter_productdetail_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='app_didikala.color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
