# Generated by Django 5.1 on 2024-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0026_alter_productdetail_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='image_url',
        ),
        migrations.AddField(
            model_name='img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/prodtctdetail/'),
        ),
    ]
