# Generated by Django 5.1 on 2024-09-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0027_remove_img_image_url_img_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifications',
            name='category',
        ),
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app_didikala.product'),
        ),
        migrations.AddField(
            model_name='img',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_didikala.product'),
        ),
        migrations.AddField(
            model_name='specifications',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='app_didikala.product'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='app_didikala.color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='descriptions',
            field=models.ManyToManyField(blank=True, related_name='products', to='app_didikala.description'),
        ),
    ]
