# Generated by Django 5.1.1 on 2024-09-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0012_division_remove_color_product_and_more'),
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_didikala.division'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_didikala.division'),
        ),
    ]
