# Generated by Django 5.1 on 2024-09-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0028_remove_specifications_category_description_product_and_more'),
        ('app_payment', '0004_alter_basketitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_didikala.color'),
        ),
    ]
