# Generated by Django 5.1.1 on 2024-09-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
