# Generated by Django 5.1 on 2024-10-10 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_didikala', '0030_alter_favorite_product'),
        ('app_social', '0007_alter_image_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disadvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_useful',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='point',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_didikala.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='suggest',
            field=models.CharField(choices=[('yes', 'پیشنهاد می\u200cکنم'), ('no', 'پیشنهاد نمی\u200cکنم'), ('no_opinion', 'نظری ندارم')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='advantages',
            field=models.ManyToManyField(null=True, related_name='comments', to='app_social.advantage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='disadvantages',
            field=models.ManyToManyField(null=True, related_name='comments', to='app_social.disadvantage'),
        ),
        migrations.DeleteModel(
            name='is_Useful',
        ),
        migrations.DeleteModel(
            name='point',
        ),
    ]
