# Generated by Django 5.1 on 2024-10-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0009_comment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='build_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='design_and_appearance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ease_of_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='features_and_capabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='innovation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='value_for_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='advantages',
            field=models.ManyToManyField(related_name='comments', to='app_social.advantage'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='disadvantages',
            field=models.ManyToManyField(related_name='comments', to='app_social.disadvantage'),
        ),
    ]
